export const ADMIN_PORTFOLIO_CREATE_REQUEST = "ADMIN_PORTFOLIO_CREATE_REQUEST";
export const ADMIN_PORTFOLIO_CREATE_SUCCESS = "ADMIN_PORTFOLIO_CREATE_SUCCESS";
export const ADMIN_PORTFOLIO_CREATE_FAIL = "ADMIN_PORTFOLIO_CREATE_FAIL";

export const ADMIN_ARTWORK_CREATE_REQUEST = "ADMIN_ARTWORK_CREATE_REQUEST";
export const ADMIN_ARTWORK_CREATE_SUCCESS = "ADMIN_ARTWORK_CREATE_SUCCESS";
export const ADMIN_ARTWORK_CREATE_FAIL = "ADMIN_ARTWORK_CREATE_FAIL";

export const ADMIN_ARTWORK_DETAILS_REQUEST = "ADMIN_ARTWORK_DETAILS_REQUEST";
export const ADMIN_ARTWORK_DETAILS_SUCCESS = "ADMIN_ARTWORK_DETAILS_SUCCESS";
export const ADMIN_ARTWORK_DETAILS_FAIL = "ADMIN_ARTWORK_DETAILS_FAIL";

export const ADMIN_DASHBOARD_LOAD_SUCCESS = "ADMIN_DASHBOARD_LOAD_SUCCESS";
export const ADMIN_DASHBOARD_LOAD_FAIL = "ADMIN_DASHBOARD_LOAD_FAIL";

export const ADMIN_LIST_MY_ARTWORK_REQUEST = "ADMIN_LIST_MY_ARTWORK_REQUEST";
export const ADMIN_LIST_MY_ARTWORK_SUCCESS = "ADMIN_LIST_MY_ARTWORK_SUCCESS";
export const ADMIN_LIST_MY_ARTWORK_FAIL = "ADMIN_LIST_MY_ARTWORK_FAIL";

export const ADMIN_LIST_MY_PORTFOLIOS_REQUEST =
  "ADMIN_LIST_MY_PORTFOLIOS_REQUEST";
export const ADMIN_LIST_MY_PORTFOLIOS_SUCCESS =
  "ADMIN_LIST_MY_PORTFOLIOS_SUCCESS";
export const ADMIN_LIST_MY_PORTFOLIOS_FAIL = "ADMIN_LIST_MY_PORTFOLIOS_FAIL";

export const ADMIN_LIST_MY_EXHIBITIONS_REQUEST =
  "ADMIN_LIST_MY_EXHIBITIONS_REQUEST";
export const ADMIN_LIST_MY_EXHIBITIONS_SUCCESS =
  "ADMIN_LIST_MY_EXHIBITIONS_SUCCESS";
export const ADMIN_LIST_MY_EXHIBITIONS_FAIL = "ADMIN_LIST_MY_EXHIBITIONS_FAIL";

export const ADMIN_LIST_MY_GALLERY_REQUEST = "ADMIN_LIST_MY_GALLERY_REQUEST";
export const ADMIN_LIST_MY_GALLERY_SUCCESS = "ADMIN_LIST_MY_GALLERY_SUCCESS";
export const ADMIN_LIST_MY_GALLERY_FAIL = "ADMIN_LIST_MY_GALLERY_FAIL";
