export const ARTISTS_LIST_REQUEST = "ARTISTS_LIST_REQUEST";
export const ARTISTS_LIST_SUCCESS = "ARTISTS_LIST_SUCCESS";
export const ARTISTS_LIST_FAIL = "ARTISTS_LIST_FAIL";

export const ARTIST_DETAILS_REQUEST = "ARTIST_DETAILS_REQUEST";
export const ARTIST_DETAILS_SUCCESS = "ARTIST_DETAILS_SUCCESS";
export const ARTIST_DETAILS_FAIL = "ARTIST_DETAILS_FAIL";
export const ARTIST_DETAILS_RESET = "ARTIST_DETAILS_RESET";

export const ARTISTS_POPULAR_REQUEST = "ARTISTS_POPULAR_REQUEST";
export const ARTISTS_POPULAR_SUCCESS = "ARTISTS_POPULAR_SUCCESS";
export const ARTISTS_POPULAR_FAIL = "ARTISTS_POPULAR_FAIL";
