export const ARTWORK_LIST_REQUEST = "ARTWORK_LIST_REQUEST";
export const ARTWORK_LIST_SUCCESS = "ARTWORK_LIST_SUCCESS";
export const ARTWORK_LIST_FAIL = "ARTWORK_LIST_FAIL";

export const ARTWORK_DETAILS_REQUEST = "ARTWORK_DETAILS_REQUEST";
export const ARTWORK_DETAILS_SUCCESS = "ARTWORK_DETAILS_SUCCESS";
export const ARTWORK_DETAILS_FAIL = "ARTWORK_DETAILS_FAIL";
export const ARTWORK_DETAILS_RESET = "ARTWORK_DETAILS_RESET";

export const ARTWORK_CREATE_REQUEST = "ARTWORK_CREATE_REQUEST";
export const ARTWORK_CREATE_SUCCESS = "ARTWORK_CREATE_SUCCESS";
export const ARTWORK_CREATE_FAIL = "ARTWORK_CREATE_FAIL";
export const ARTWORK_CREATE_RESET = "ARTWORK_CREATE_RESET";

export const ARTWORK_UPDATE_REQUEST = "ARTWORK_UPDATE_REQUEST";
export const ARTWORK_UPDATE_SUCCESS = "ARTWORK_UPDATE_SUCCESS";
export const ARTWORK_UPDATE_FAIL = "ARTWORK_UPDATE_FAIL";
export const ARTWORK_UPDATE_RESET = "ARTWORK_UPDATE_RESET";

export const ARTWORK_DELETE_REQUEST = "ARTWORK_DELETE_REQUEST";
export const ARTWORK_DELETE_SUCCESS = "ARTWORK_DELETE_SUCCESS";
export const ARTWORK_DELETE_FAIL = "ARTWORK_DELETE_FAIL";

export const ARTWORK_CREATE_REVIEW_REQUEST = "ARTWORK_CREATE_REVIEW_REQUEST";
export const ARTWORK_CREATE_REVIEW_SUCCESS = "ARTWORK_CREATE_REVIEW_SUCCESS";
export const ARTWORK_CREATE_REVIEW_FAIL = "ARTWORK_CREATE_REVIEW_FAIL";
export const ARTWORK_CREATE_REVIEW_RESET = "ARTWORK_CREATE_REVIEW_RESET";

export const ARTWORK_GET_RELATED_REQUEST = "ARTWORK_GET_RELATED_REQUEST";
export const ARTWORK_GET_RELATED_SUCCESS = "ARTWORK_GET_RELATED_SUCCESS";
export const ARTWORK_GET_RELATED_FAIL = "ARTWORK_GET_RELATED_FAIL";
export const ARTWORK_GET_RELATED_RESET = "ARTWORK_GET_RELATED_RESET";

export const ARTWORK_BY_TITLE_SUCCESS = "ARTWORK_BY_TITLE_SUCCESS";
export const ARTWORK_BY_TITLE_FAIL = "ARTWORK_BY_TITLE_FAIL";

export const ARTWORK_BY_ARTIST_SUCCESS = "ARTWORK_BY_ARTIST_SUCCESS";
export const ARTWORK_BY_ARTIST_FAIL = "ARTWORK_BY_ARTIST_FAIL";

export const ARTWORK_BY_EXHIBITION_SUCCESS = "ARTWORK_BY_EXHIBITION_SUCCESS";
export const ARTWORK_BY_EXHIBITION_FAIL = "ARTWORK_BY_EXHIBITION_FAIL";

export const ARTWORK_BY_ART_TYPE_SUCCESS = "ARTWORK_BY_ART_TYPE_SUCCESS";
export const ARTWORK_BY_ART_TYPE_FAIL = "ARTWORK_BY_ART_TYPE_FAIL";

export const ARTWORK_PRICE_RANGE_SUCCESS = "ARTWORK_PRICE_RANGE_SUCCESS";
export const ARTWORK_PRICE_RANGE_FAIL = "ARTWORK_PRICE_RANGE_FAIL";

export const ARTWORK_SEARCH_REQUEST = "ARTWORK_SEARCH_REQUEST";
export const ARTWORK_SEARCH_RESET = "ARTWORK_SEARCH_RESET";
export const ARTWORK_SEARCH_FAIL = "ARTWORK_SEARCH_FAIL";

export const ARTWORK_TOP_REQUEST = "ARTWORK_TOP_REQUEST";
export const ARTWORK_TOP_SUCCESS = "ARTWORK_TOP_SUCCESS";
export const ARTWORK_TOP_FAIL = "ARTWORK_TOP_FAIL";
