export const ADMIN_LIST_MY_EXHIBITIONS_REQUEST =
  "ADMIN_LIST_MY_EXHIBITIONS_REQUEST";
export const ADMIN_LIST_MY_EXHIBITIONS_SUCCESS =
  "ADMIN_LIST_MY_EXHIBITIONS_SUCCESS";
export const ADMIN_LIST_MY_EXHIBITIONS_FAIL = "ADMIN_LIST_MY_EXHIBITIONS_FAIL";

export const EXHIBITION_LIST_REQUEST = "EXHIBITION_LIST_REQUEST";
export const EXHIBITION_LIST_SUCCESS = "EXHIBITION_LIST_SUCCESS";
export const EXHIBITION_LIST_FAIL = "EXHIBITION_LIST_FAIL";

export const EXHIBITION_DETAILS_REQUEST = "EXHIBITION_DETAILS_REQUEST";
export const EXHIBITION_DETAILS_SUCCESS = "EXHIBITION_DETAILS_SUCCESS";
export const EXHIBITION_DETAILS_FAIL = "EXHIBITION_DETAILS_FAIL";

export const EXHIBITION_CREATE_REQUEST = "EXHIBITION_CREATE_REQUEST";
export const EXHIBITION_CREATE_SUCCESS = "EXHIBITION_CREATE_SUCCESS";
export const EXHIBITION_CREATE_FAIL = "EXHIBITION_CREATE_FAIL";
export const EXHIBITION_CREATE_RESET = "EXHIBITION_CREATE_RESET";

export const EXHIBITION_UPDATE_REQUEST = "EXHIBITION_UPDATE_REQUEST";
export const EXHIBITION_UPDATE_SUCCESS = "EXHIBITION_UPDATE_SUCCESS";
export const EXHIBITION_UPDATE_FAIL = "EXHIBITION_UPDATE_FAIL";
export const EXHIBITION_UPDATE_RESET = "EXHIBITION_UPDATE_RESET";

export const EXHIBITION_DELETE_REQUEST = "EXHIBITION_DELETE_REQUEST";
export const EXHIBITION_DELETE_SUCCESS = "EXHIBITION_DELETE_SUCCESS";
export const EXHIBITION_DELETE_FAIL = "EXHIBITION_DELETE_FAIL";

export const EXHIBITION_CREATE_REVIEW_REQUEST =
  "EXHIBITION_CREATE_REVIEW_REQUEST";
export const EXHIBITION_CREATE_REVIEW_SUCCESS =
  "EXHIBITION_CREATE_REVIEW_SUCCESS";
export const EXHIBITION_CREATE_REVIEW_FAIL = "EXHIBITION_CREATE_REVIEW_FAIL";
export const EXHIBITION_CREATE_REVIEW_RESET = "EXHIBITION_CREATE_REVIEW_RESET";
