//upload actions
export const UPLOAD_SET_PROGRESS = "UPLOAD_SET_PROGRESS";
export const UPLOAD_SET_PROGRESS_FAIL = "UPLOAD_SET_PROGRESS_FAIL";
export const UPLOAD_SET_MESSAGE = "UPLOAD_SET_MESSAGE";
export const UPLOAD_SET_MESSAGE_FAIL = "UPLOAD_SET_MESSAGE_FAIL";

export const UPLOAD_IMAGE_ARTWORK_REQUEST = "UPLOAD_IMAGE_ARTWORK_REQUEST";
export const UPLOAD_IMAGE_ARTWORK_SUCCESS = "UPLOAD_IMAGE_ARTWORK_SUCCESS";
export const UPLOAD_IMAGE_ARTWORK_FAIL = "UPLOAD_IMAGE_ARTWORK_FAIL";
export const UPLOAD_IMAGE_ARTWORK_RESET = "UPLOAD_IMAGE_ARTWORK_RESET";

export const UPLOAD_S3_URL_REQUEST = "UPLOAD_S3_URL_REQUEST";
export const UPLOAD_S3_URL_SUCCESS = "UPLOAD_S3_URL_SUCCESS";
export const UPLOAD_S3_URL_FAIL = "UPLOAD_S3_URL_FAIL";
export const UPLOAD_S3_URL_RESET = "UPLOAD_S3_URL_RESET";

export const UPLOAD_IMAGE_TO_S3_REQUEST = "UPLOAD_IMAGE_TO_S3_REQUEST";
export const UPLOAD_IMAGE_TO_S3_SUCCESS = "UPLOAD_IMAGE_TO_S3_SUCCESS";
export const UPLOAD_IMAGE_TO_S3_FAIL = "UPLOAD_IMAGE_TO_S3_FAIL";
